/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as BedroomRouteImport } from './routes/bedroom'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DecorIdeasRouteImport } from './routes/decor-ideas'
import { Route as DiningRoomRouteImport } from './routes/dining-room'
import { Route as HomeOfficeRouteImport } from './routes/home-office'
import { Route as HomeOrganizationRouteImport } from './routes/home-organization'
import { Route as LivingRoomRouteImport } from './routes/living-room'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SmallSpacesRouteImport } from './routes/small-spaces'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ProductGuidesIndexRouteImport } from './routes/product-guides/index'
import { Route as ProductGuidesSlugRouteImport } from './routes/product-guides/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const BedroomRoute = BedroomRouteImport.update({
  id: '/bedroom',
  path: '/bedroom',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DecorIdeasRoute = DecorIdeasRouteImport.update({
  id: '/decor-ideas',
  path: '/decor-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoomRoute = DiningRoomRouteImport.update({
  id: '/dining-room',
  path: '/dining-room',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOfficeRoute = HomeOfficeRouteImport.update({
  id: '/home-office',
  path: '/home-office',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOrganizationRoute = HomeOrganizationRouteImport.update({
  id: '/home-organization',
  path: '/home-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingRoomRoute = LivingRoomRouteImport.update({
  id: '/living-room',
  path: '/living-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SmallSpacesRoute = SmallSpacesRouteImport.update({
  id: '/small-spaces',
  path: '/small-spaces',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductGuidesIndexRoute = ProductGuidesIndexRouteImport.update({
  id: '/product-guides/',
  path: '/product-guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductGuidesSlugRoute = ProductGuidesSlugRouteImport.update({
  id: '/product-guides/$slug',
  path: '/product-guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/bedroom': typeof BedroomRoute
  '/contact': typeof ContactRoute
  '/decor-ideas': typeof DecorIdeasRoute
  '/dining-room': typeof DiningRoomRoute
  '/home-office': typeof HomeOfficeRoute
  '/home-organization': typeof HomeOrganizationRoute
  '/living-room': typeof LivingRoomRoute
  '/privacy': typeof PrivacyRoute
  '/small-spaces': typeof SmallSpacesRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/product-guides/$slug': typeof ProductGuidesSlugRoute
  '/product-guides/': typeof ProductGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/bedroom': typeof BedroomRoute
  '/contact': typeof ContactRoute
  '/decor-ideas': typeof DecorIdeasRoute
  '/dining-room': typeof DiningRoomRoute
  '/home-office': typeof HomeOfficeRoute
  '/home-organization': typeof HomeOrganizationRoute
  '/living-room': typeof LivingRoomRoute
  '/privacy': typeof PrivacyRoute
  '/small-spaces': typeof SmallSpacesRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/product-guides/$slug': typeof ProductGuidesSlugRoute
  '/product-guides': typeof ProductGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/bedroom': typeof BedroomRoute
  '/contact': typeof ContactRoute
  '/decor-ideas': typeof DecorIdeasRoute
  '/dining-room': typeof DiningRoomRoute
  '/home-office': typeof HomeOfficeRoute
  '/home-organization': typeof HomeOrganizationRoute
  '/living-room': typeof LivingRoomRoute
  '/privacy': typeof PrivacyRoute
  '/small-spaces': typeof SmallSpacesRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/product-guides/$slug': typeof ProductGuidesSlugRoute
  '/product-guides/': typeof ProductGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/bedroom'
    | '/contact'
    | '/decor-ideas'
    | '/dining-room'
    | '/home-office'
    | '/home-organization'
    | '/living-room'
    | '/privacy'
    | '/small-spaces'
    | '/terms'
    | '/articles/$slug'
    | '/product-guides/$slug'
    | '/product-guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/bedroom'
    | '/contact'
    | '/decor-ideas'
    | '/dining-room'
    | '/home-office'
    | '/home-organization'
    | '/living-room'
    | '/privacy'
    | '/small-spaces'
    | '/terms'
    | '/articles/$slug'
    | '/product-guides/$slug'
    | '/product-guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/bedroom'
    | '/contact'
    | '/decor-ideas'
    | '/dining-room'
    | '/home-office'
    | '/home-organization'
    | '/living-room'
    | '/privacy'
    | '/small-spaces'
    | '/terms'
    | '/articles/$slug'
    | '/product-guides/$slug'
    | '/product-guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  BedroomRoute: typeof BedroomRoute
  ContactRoute: typeof ContactRoute
  DecorIdeasRoute: typeof DecorIdeasRoute
  DiningRoomRoute: typeof DiningRoomRoute
  HomeOfficeRoute: typeof HomeOfficeRoute
  HomeOrganizationRoute: typeof HomeOrganizationRoute
  LivingRoomRoute: typeof LivingRoomRoute
  PrivacyRoute: typeof PrivacyRoute
  SmallSpacesRoute: typeof SmallSpacesRoute
  TermsRoute: typeof TermsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ProductGuidesSlugRoute: typeof ProductGuidesSlugRoute
  ProductGuidesIndexRoute: typeof ProductGuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedroom': {
      id: '/bedroom'
      path: '/bedroom'
      fullPath: '/bedroom'
      preLoaderRoute: typeof BedroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decor-ideas': {
      id: '/decor-ideas'
      path: '/decor-ideas'
      fullPath: '/decor-ideas'
      preLoaderRoute: typeof DecorIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining-room': {
      id: '/dining-room'
      path: '/dining-room'
      fullPath: '/dining-room'
      preLoaderRoute: typeof DiningRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-office': {
      id: '/home-office'
      path: '/home-office'
      fullPath: '/home-office'
      preLoaderRoute: typeof HomeOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-organization': {
      id: '/home-organization'
      path: '/home-organization'
      fullPath: '/home-organization'
      preLoaderRoute: typeof HomeOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living-room': {
      id: '/living-room'
      path: '/living-room'
      fullPath: '/living-room'
      preLoaderRoute: typeof LivingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/small-spaces': {
      id: '/small-spaces'
      path: '/small-spaces'
      fullPath: '/small-spaces'
      preLoaderRoute: typeof SmallSpacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-guides/': {
      id: '/product-guides/'
      path: '/product-guides'
      fullPath: '/product-guides/'
      preLoaderRoute: typeof ProductGuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-guides/$slug': {
      id: '/product-guides/$slug'
      path: '/product-guides/$slug'
      fullPath: '/product-guides/$slug'
      preLoaderRoute: typeof ProductGuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  BedroomRoute: BedroomRoute,
  ContactRoute: ContactRoute,
  DecorIdeasRoute: DecorIdeasRoute,
  DiningRoomRoute: DiningRoomRoute,
  HomeOfficeRoute: HomeOfficeRoute,
  HomeOrganizationRoute: HomeOrganizationRoute,
  LivingRoomRoute: LivingRoomRoute,
  PrivacyRoute: PrivacyRoute,
  SmallSpacesRoute: SmallSpacesRoute,
  TermsRoute: TermsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ProductGuidesSlugRoute: ProductGuidesSlugRoute,
  ProductGuidesIndexRoute: ProductGuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
